### ISSUE TITLE
Is there any way to get file uploads to s3 working?

### ISSUE THREAD

**Issue by kitsune7** [EddyVerbruggen/nativescript-aws#2]
I want to use this plugin to upload video files to s3 if at all possible, but there's no way to do it from nativescript or this plugin as far as I can tell.

**Comment by EddyVerbruggen** [comment]
What have you tried already? And what's the error?

I [tested listing S3 buckets](https://github.com/EddyVerbruggen/nativescript-aws/blob/master/demo/app/main-view-model.ts#L32-L47).

**Comment by kitsune7** [comment]
For this plugin I've tried the following code:
```
var AWS = require("nativescript-aws");

var AWS_accessKeyId = "-----";
var AWS_secretAccessKey = "-----";
var AWS_S3_bucket = "-----";
var AWS_S3_bucket_key = "-----";
var s3 = new AWS.S3();

AWS.config.update({
    credentials: {
        accessKeyId: AWS_accessKeyId,
        secretAccessKey: AWS_secretAccessKey
    }
});
```
...
```
console.log("Attempting to upload video...");
var filename = filepath.replace(/^.*[\\\/]/, '');

console.log("Video exists?", fs.File.exists(filepath));
var videoFile = fs.File.fromPath(filepath);
var videoBinary = videoFile.readSync(function (e) {
    console.log("It broke in the binary...");
    console.log(e);
    throw Error(e);
});

var params = {
    Bucket: AWS_S3_bucket,
    Key: AWS_S3_bucket_key,
    Body: videoBinary
};
s3.upload(params, function(err, data) {
    console.log(err, data);
});
```

I get this error message when running it:
```
An uncaught Exception occurred on "main" thread.
com.tns.NativescriptException: Failed to find module: "crypto", relative to app/tns_modules/
  at com.tns.Module.resolvePathHelper(Module.java:159)
  at com.tns.Module.resolvePath(Module.java:60)
  at com.tns.Runtime.callJSMethodNative(NativeMethod)
  at ...
```

I've also tried using the `nativescript-background-http` plugin as well, but it's never worked for me.
http://stackoverflow.com/questions/42013187/how-do-you-upload-a-video-to-a-node-js-server-in-nativescript

**Comment by EddyVerbruggen** [comment]
Hmm, that `crypto` thing should be fixed by this plugin. Can you please check if that 'list buckets' code does work for you? Just throw in [these lines](https://github.com/EddyVerbruggen/nativescript-aws/blob/master/demo/app/main-view-model.ts#L32-L47) instead of the upload code.

**Comment by kitsune7** [comment]
That code doesn't work for me either. I get the same error.

**Comment by ghost** [comment]
import * as AWS from "nativescript-aws";

AWS.config.region = 'eu-west-1';
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
      IdentityPoolId: '----',
 });

var bucket = new AWS.S3();

var userObj = {
            userKey: "key",
            email: "email",
}

var params = {
            Bucket: 'dealerdb/',
            Key: "profileDetails",
            Body: JSON.stringify(userObj)
 };

 bucket.upload( params, function (err, result){
            if (!err) {
                console.log("page change");
            } else {
                console.log("error in page change",err);
            }
        });

I got error “NetworkingError: Missing credentials in config”

Any help please??

**Comment by zahid-dapperapps** [comment]
anyone solved this yet?
