### ISSUE TITLE
Error Compatibility patch

### ISSUE THREAD

**Issue by DevZatokio** [EddyVerbruggen/nativescript-aws#9]
**********************************************************
******* start nativescript-aws compatibility patch *******
**********************************************************
Error occurred: { Error: Cannot find module './node_modules/aws-sdk/package.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at patchPackageJsonMainAndFetchBrowserNode (/Users/xxxx/Desktop/xxxx App/xxx xxxx/node_modules/nativescript-aws/postinstall.js:42:14)
    at patchPackage (/Users/camiloorellana/Desktop/Communis App/Mejor Municipio/node_modules/nativescript-aws/postinstall.js:57:21)
    at Object.<anonymous> (/Users/xx/Desktop/xxxx App/xxxxxx/node_modules/nativescript-aws/postinstall.js:97:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32) code: 'MODULE_NOT_FOUND' }

**********************************************************
*******  end nativescript-aws compatibility patch  *******
**********************************************************

**Comment by EddyVerbruggen** [comment]
Say what?

**Comment by DevZatokio** [comment]
it's a mistake ? or what is going?

**Comment by EddyVerbruggen** [comment]
I have no idea what you mean with this issue report.

**Comment by DevZatokio** [comment]
Why does this error occur when installing the plugin?
